### ISSUE TITLE
Read3.fastq.gz file not found

### ISSUE THREAD

**Issue by ysu2015** [chensong611/SNARE_prep#1]
Hi Song,
I am very excited to found you guys adapt the scATACseq with Drop-seq platform, which will be very useful to the single community. I tried to download the data from the paper to take a close look. After reading through the manuscript, I get confused that there should be 3 files, read1/2/3 in the sequencing results. But I kind of not sure how to get the Read3.fastq file from GEO. Is that possible you can guide me how to do that? Thanks a lot.

Y

**Comment by chensong611** [comment]
Hi Y,

For some reason, the P0 datasets are not properly stored in SRA. So I suggest you try the adult brain cortex datasets first (e.g., https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR9672090 and https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR9672089). You can download the original fastq files under the “Data access” tag. For each SNARE-seq experiment, we have both expression data (Read1, 30bp, for cell barcode; Read2, 80bp or 50 bp, for cDNA mapping) and chromatin accessibility data (Read1, 30bp, for cell barcode; Read2 and Read3, 75 bp, for pair-end mapping of chromatin). Hope that helps!

Song

**Comment by ysu2015** [comment]
That is great. Thank you for your help.

Y

**Comment by ysu2015** [comment]
One more question, you have 2 set of barcodes on both P50X-TSO and Ad2.1_XXX. As my understanding, Ad2.1 used for barcoded samples/runs. What dose P50X-TSO barcode for?

Y

**Comment by chensong611** [comment]
P50X is not absolutely required. We just use that to expand the barcode space so that we can pool different types of libraries together for sequencing.

Song

**Comment by ysu2015** [comment]
Got it. Thanks a lot.

Y
